# ssd-hostpath-sc.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /var/dcs/storage
volumeBindingMode: WaitForFirstConsumer #Immediate