# registry.facebook.com:5443
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5yb2xlaXQuY29tOjU0NDMiOnsidXNlcm5hbWUiOiJkY3N1cmFuaSIsInBhc3N3b3JkIjoiYTgyOThhZWYtNTgwMi00N2EzLWI3YmYtMmZjNmI2OWZkODU4IiwiZW1haWwiOiJkY3N1cmFuaUBnbWFpbCIsImF1dGgiOiJaR056ZFhKaGJtazZZVGd5T1RoaFpXWXROVGd3TWkwME4yRXpMV0kzWW1ZdE1tWmpObUkyT1daa09EVTQi19
kind: Secret
metadata:
  name: docker-sec
  namespace: aprod
type: kubernetes.io/dockerconfigjson